config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, except: [:show, :update] 
  get '/users/:id/detail', to: 'users#detail', as: 'user_detail'
  get '/users/home', to: 'users#home', as: 'user_home'
  post '/users/give_reward', to: 'users#give_reward'
  patch '/users/claim_reward', to: 'users#claim_reward'
  root 'maps#index'

  resources :maps
  post '/maps/create_simple', to: 'maps#create_simple', as: 'create_simple_map'
  get '/maps/:id/map_to_json', to: 'maps#map_to_json'

  resources :items
end

app/models/map.rb
class Map < ApplicationRecord
  def generate_minesweeper_map(rows, cols, num_mines)
    tiles = Array.new(rows) { Array.new(cols, 0) }
    mines = Set.new

    while mines.size < num_mines
      row = rand(rows)
      col = rand(cols)
      mines.add([row, col])
      tiles[row][col] = -1
    end

    mines.each do |mine|
      row, col = mine

      (-1..1).each do |dx|
        (-1..1).each do |dy|
          next if dx == 0 && dy == 0

          nx = row + dx
          ny = col + dy

          next if nx < 0 || nx >= rows || ny < 0 || ny >= cols
          next if tiles[nx][ny] == -1

          tiles[nx][ny] += 1
        end
      end
    end

    self.tiles = tiles
    save
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @maps = Map.all
    if current_user
      redirect_to user_home_path
    end
  end

  def show
    @map = Map.find(params[:id])
  end

  def new
    @map = Map.new
  end

  def destroy
    @map = Map.find(params[:id])
    @map.destroy

    redirect_to root_path
  end

  def create_simple
    difficulty = params.dig(:map, :difficulty)
    puts 'hahaha' + difficulty.inspect
    case difficulty
    when 'easy'
      rows, cols, num_mines = 9, 9, 10
    when 'medium'
      rows, cols, num_mines = 16, 16, 40
    when 'hard'
      rows, cols, num_mines = 30, 16, 99
    when 'extreme'
      rows, cols, num_mines = 30, 24, 160
    else
      rows, cols, num_mines = 9, 9, 10
    end
    @map = Map.new(map_params)
    @map.generate_minesweeper_map(rows, cols, num_mines)
    if @map.save
      current_user.update(map_id: @map.id)
      redirect_to @map, notice: 'Have Fun !'
    else
      render json: @map.errors, status: :unprocessable_entity
    end
  end

  def map_to_json
    @map = Map.find(params[:id])
    render json: @map
  end

  private

  def map_params
    params.require(:map).permit(:name)
  end
end

app/views/maps/index.html.haml
%h1 MSR
- @maps.each do |map|
  %br
  = link_to map.name.to_s, map_path(map.id)
  = link_to 'Destroy', map_path(map), data: { turbo_method: :delete }

%br
%br
= form_for(Map.new, url: create_simple_map_path) do |form|
  %div
    = form.label :name
    = form.text_field :name

  %div
    = form.submit 'Create Map'

app/views/maps/new.html.haml
%h1 New Map

= form_with(model: @map, url: create_simple_map_path, local: true) do |form|
  %div
  
    = form.label :name
    = form.text_field :name

  %div
    = form.submit 'Create Map'

app/views/maps/show.html.haml
= stylesheet_link_tag 'tile'
= stylesheet_link_tag 'cell'
= stylesheet_link_tag 'card'

.displayer
  .card.m-top-3
    .pricing-block-content
      .d-flex.home-text{ data: { controller: 'maps--render', 'maps--render-target': 'data' } }
        %h1
          = @map.name

        %div
          .mapDiv.game-inside{ data: { 'maps--render-target': 'mapDiv' } }

        .d-none{ data: { 'maps--render-target': 'won' } }
          You won