config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, except: [:show, :update] 
  get '/users/:id/detail', to: 'users#detail', as: 'user_detail'
  get '/users/home', to: 'users#home', as: 'user_home'
  post '/users/give_reward', to: 'users#give_reward'
  patch '/users/claim_reward', to: 'users#claim_reward'
  root 'maps#index'

  resources :maps
  post '/maps/create_simple', to: 'maps#create_simple', as: 'create_simple_map'
  get '/maps/:id/map_to_json', to: 'maps#map_to_json'

  resources :items
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MSR
    %meta{ name: 'viewport', content: 'width=device-width,initial-scale=1' }
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'tile'
    = stylesheet_link_tag 'bootstrap'
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags
  %body

    .upper-bar.upper-container
      %div
        = link_to 'home', current_user.nil? ? root_path : user_home_path, class: 'simple-white-link'
        = link_to 'shop', items_path, class: 'simple-white-link'
      - if current_user.nil?
        = link_to 'Sign in', new_user_session_path, class: 'simple-white-link'
      - else
        Connected as #{current_user.username},
        Current balance: #{current_user.balance.to_i}
        .user-links
          = link_to 'Profile', user_detail_path(current_user.id), class: 'simple-white-link'
          = link_to 'Sign-Out', destroy_user_session_path, class: 'simple-white-link', data: { turbo_method: :delete }
    = yield